import { DefaultTheme } from "styled-components";

export const lightTheme: DefaultTheme = {
  body: "#f0f0f0",
  text: "#023e48",
  textSecondary: "#535353",
  primaryColor: "#ffa948",
  secondaryColor: "#1b666b",
  accentColor: "#a64510",
  backgroundCard: "#FFFFFF",
  backgroundNavbar: "#FFFFFF",
  linkColor: "#ffa948",
  titleColor: "#023e48",
  buttonBackground: "#ffa948",
  buttonTextColor: "#FFFFFF",
  buttonSecondaryBackground: "#1b666b",
  buttonSecondaryTextColor: "#FFFFFF",
  fontFamily: '"Arial", sans-serif',
  theme: "light",
  cardShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
};

export const darkTheme: DefaultTheme = {
  body: "#071724",
  text: "#E0E0E0",
  textSecondary: "#CCCCCC",
  primaryColor: "#ffa948",
  secondaryColor: "#1b666b",
  accentColor: "#a64510",
  backgroundCard: "#103048",
  backgroundNavbar: "#023e48",
  linkColor: "#ffa948",
  titleColor: "#E0E0E0",
  buttonBackground: "#ffa948",
  buttonTextColor: "#071724",
  buttonSecondaryBackground: "#1b666b",
  buttonSecondaryTextColor: "#FFFFFF",
  fontFamily: '"Arial", sans-serif',
  theme: "dark",
  cardShadow: "0 4px 8px rgba(0, 0, 0, 0.2)",
};
